# Generated by Django 5.2.4 on 2025-07-22 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=254)),
                ('Contact', models.IntegerField()),
                ('Image', models.ImageField(upload_to='images/')),
                ('Documents', models.FileField(upload_to='documents/')),
                ('Video', models.FileField(upload_to='video/')),
                ('Password', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Form_Data',
            },
        ),
    ]
